services:
  mongo:
    build: ./mongodb_container
    container_name: emotitrack-mongo
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  chat-bot-api:
    image: python:3.11-slim
    container_name: emotitrack-chat-bot-api
    working_dir: /app
    volumes:
      - ./chat_bot_api:/app
    environment:
      MONGO_URI: mongodb://mongo:27017/
      PYTHONUNBUFFERED: "1"
    depends_on:
      mongo:
        condition: service_healthy
    command: >-
      sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    restart: unless-stopped

  whatsapp-bot:
    image: python:3.11-slim
    container_name: emotitrack-whatsapp-bot
    working_dir: /workspace/whatsapp_bot
    volumes:
      - ./:/workspace
    env_file:
      - whatsapp_bot/.env
    environment:
      URL_CHAT_BOT_API: http://chat-bot-api:8000
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: /workspace
    depends_on:
      chat-bot-api:
        condition: service_started
    command: >-
      sh -c "pip install --no-cache-dir -r requirements.txt && python -m whatsapp_bot.app"
    ports:
      - "5000:5000"
    restart: unless-stopped

volumes:
  mongo-data:
